### PR TITLE
Updated paths to path and created array

### PR DESCRIPTION
**Pull request by escabar**

### CODE REVIEW

**Comment by thomasmitchell** [comment]
`paths` has been added since the last release of doomsday, and so that should be left as `paths`. Can I get a little more context on what behavior you were seeing that brought you here?

**Comment by escabar** [comment]
I came across 2 issues:
1- the object _.cert doesn't contain paths, it does contain path. 
2- _.paths.forEach(function(path) {
			  var backendFound = false;
			  var i = 0;
                          .......
   is failing thus the array
Thanks.

**Comment by escabar** [comment]
On a separate note: What is the best way to display all the certs in the Web UI. Currently only showing expired certs (Note: haven't tested with expiring certs. Only testing with valid and expired)

S.

**Comment by thomasmitchell** [comment]
"All the certs" won't be in the initial release of the UI. Planning to have a "show more" button at the bottom to have it expand out more over time, implemented shortly afterward.

As for paths not being in the return value...
```go
type CacheItem struct {
	Paths      []CacheItemPath `json:"paths"`
	CommonName string          `json:"common_name"`
	NotAfter   int64           `json:"not_after"`
}
```
This is the struct that gets marshalled into the json response - it does have "paths". I also can't replicate what you're seeing on the master branch build. How did you build this?

**Comment by escabar** [comment]
I'm running the DD server in Pivotal Cloud Foundry using the binary buildpack, this is working well and the CLI and API endpoints are working correctly. 

I'm running the Web UI as a separate PCF App using the staticfile buildpack. This is the component that did not work due to the items above. The PR changes resolved my issues.

**Comment by thomasmitchell** [comment]
ah, now I understand. :)
so, I can't merge this, because it will break existing code. A release will come out soon that will make it so that the Web UI is in the binary and you won't have to run two separate apps.

The actual problem here is that you're running a Web UI made for 0.6.0 against a 0.5.0 server. I'll try to get the release out ASAP for you.

**Comment by escabar** [comment]
Thanks. Much Appreciated.

**Comment by thomasmitchell** [comment]
The version with the web UI embedded has been released.

**Pull request closed without merging**
