### PR TITLE
update jquery to 3.5.1

### PR DESCRIPTION
**Pull request by scottillogical**
jquery < 3.5.0 has some vulnerabilities

### CODE REVIEW

**Comment by thomasmitchell** [comment]
I'm all for the JQuery bump. Why the catch -> fail changes, though? I think the doomsday client parses out the JQuery.Promise object and throws its own APIError object instead, which should get handled by the generic JS Promise interface. I don't have strong opinions on it being written either way, but I'm curious as to what you ran into where you had to change it.

**Comment by scottillogical** [comment]
Hey Thomas! I only changed the promise code because I got these errors running make all after upgrading jQuery
```
web/ts/client.ts:41:3 - error TS2741: Property '[Symbol.toStringTag]' is missing in type 'PromiseBase<AuthMethod, never, never, never, never, never, never, never, never, never, never, never>' but required in type 'Promise<AuthMethod>'.

 41     return this.doRequest("GET", "/v1/info")
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 42             .then(
    ~~~~~~~~~
...
 44                     this.handleFailure
    ~~~~~~~~~~~~~~~~~~~~~~
 45             );
    ~~~~~
```
I attempted to fix this error by using a jQuery.Promise instead but have no idea what the best way to handle this error is

**Comment by thomasmitchell** [comment]
Seems like Typescript being funky. Maybe later Typescript versions did a thing. Maybe my code is bad. My code is probably bad.

Here's where I'm at; I've realized recently that since I changed this to Typescript and I can transpile things, I don't really _need_ JQuery at all, really, and I was planning to rip it out. Let me make a spike tonight where I'll see how trivial it is to just use raw JS instead, and if that works out, I'll do that (and the JQuery vulnerability is _gone_), and if it proves to be too big of a pain for a quick thing, I'll figure out what's going on with the type complaints.

**Comment by thomasmitchell** [comment]
Alright! @scottillogical 
A compromise has been reached. I've fixed _my_ code to not break on JQuery Promises anymore. JQuery would be a pain in the ass to remove entirely as a quick little thing because of another library.
If you drop the `web/ts` directory changes you had to make, rebase off master, rebuild, and push, then I'll pull this in. I'm sorry for all the trouble.

**Comment by scottillogical** [comment]
@thomasmitchell thanks Thomas!  I rebased this morning looks good

**Comment by thomasmitchell** [comment]
lgtm. thank for you for your patience.

**Comment by scottillogical** [comment]
@thomasmitchell can you release a boshrelease version that includes this change?  Thank you!

**Comment by thomasmitchell** [comment]
https://github.com/doomsday-project/doomsday-boshrelease/releases/tag/v0.9.2

it is done.

**Pull request merged**
